services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--no-deprecation

  api:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./database/migrations:/app/database/migrations
      - .:/app
    environment:
      - DB_URL=sqlite+aiosqlite:///./data/nursia.db
      - PYTHONPATH=/app
    command: ./scripts/startup.sh
    depends_on:
      - frontend
